<?php

namespace App\Actions\System;

use App\Models\Ciian\System\Page;
use App\Models\Ciian\System\System;
use App\Support\SystemPagePath;
use Illuminate\Support\Facades\File;
use Illuminate\Validation\ValidationException;

/**
 * Writes the React file a published page is served from.
 *
 * A created system owns a folder under `resources/js/pages/` named after its
 * slug, so its pages resolve as `{system}/{page}` — the same way publishing a
 * table generates its Eloquent model. The files are build output: they are
 * gitignored, and republishing overwrites them.
 */
class GeneratePageFile
{
    public function __construct(private SystemPagePath $paths) {}

    /**
     * Create the system's page folder, whether or not it has published pages yet.
     */
    public function ensureDirectory(System $system): void
    {
        $directory = $this->paths->directoryFor($system);

        if (! File::isDirectory($directory)) {
            File::ensureDirectoryExists($directory);
        }
    }

    /**
     * Write one published page's file.
     */
    public function handle(System $system, Page $page): void
    {
        $this->ensureDirectory($system);

        $path = $this->paths->fileFor($system, $page);

        if (File::put($path, $this->render($system, $page)) === false) {
            throw ValidationException::withMessages([
                'shape' => __('The page could not be written to :path.', [
                    'path' => $this->paths->relative($path),
                ]),
            ]);
        }
    }

    /**
     * Write every page of a system that is currently published, and create the
     * folder even when none are.
     */
    public function handleSystem(System $system): void
    {
        $this->ensureDirectory($system);

        foreach ($system->pages()->where('status', Page::STATUS_PUBLISHED)->get() as $page) {
            $this->handle($system, $page);
        }
    }

    /**
     * Remove a page's file. The row is the source of truth, so a missing file is
     * not an error — a fresh checkout starts with no generated pages at all.
     */
    public function remove(System $system, Page $page): void
    {
        $path = $this->paths->fileFor($system, $page);

        if (File::exists($path) && ! File::delete($path)) {
            throw ValidationException::withMessages([
                'page' => __('The page was removed, but :path could not be deleted. Remove it manually.', [
                    'path' => $this->paths->relative($path),
                ]),
            ]);
        }
    }

    /**
     * Follow a still-unpublished system's slug to its new folder, so its already
     * generated pages do not strand under the old name.
     */
    public function moveDirectory(string $fromSlug, string $toSlug): void
    {
        if ($fromSlug === $toSlug) {
            return;
        }

        $from = $this->paths->directoryForSlug($fromSlug);
        $to = $this->paths->directoryForSlug($toSlug);

        if (! File::isDirectory($from) || File::isDirectory($to)) {
            return;
        }

        File::moveDirectory($from, $to);
    }

    private function render(System $system, Page $page): string
    {
        $component = $this->paths->componentNameFor($system, $page);
        $title = addslashes($page->name);
        $name = $this->paths->pageNameFor($system, $page);

        return <<<TSX
        import { Head } from '@inertiajs/react';

        /**
         * Generated by Ciian for the "{$page->name}" page of {$system->name}.
         *
         * Do not edit by hand — publishing the page from the System Builder
         * overwrites this file. Page name: `{$name}`.
         */
        export default function {$component}() {
            return (
                <>
                    <Head title="{$title}" />

                    <div className="px-4 py-6">
                        {/* Blocks placed on this page render here. */}
                    </div>
                </>
            );
        }

        TSX;
    }
}
