<?php

/*
|--------------------------------------------------------------------------
| Guest pages (unauthenticated)
|--------------------------------------------------------------------------
*/
require __DIR__.'/guest.php';

/*
|--------------------------------------------------------------------------
| Account settings (all authenticated users)
|--------------------------------------------------------------------------
*/
require __DIR__.'/settings.php';

/*
|--------------------------------------------------------------------------
| Platform administration (developers / admins)
|--------------------------------------------------------------------------
*/
require __DIR__.'/admin.php';

/*
|--------------------------------------------------------------------------
| Created systems (authenticated system pages)
|--------------------------------------------------------------------------
|
| Generated by App\Actions\System\GenerateSystemRoutes when a system or one of
| its pages is published, and gitignored like the page files it points at. A
| fresh checkout has no such file until something is published, so the require
| is guarded; run `php artisan ciian:sync-routes` to rebuild it from the
| database after a checkout or deploy.
|
| Required last on purpose: a platform route above always wins a tie against a
| system's URL prefix.
|
*/
if (file_exists(__DIR__.'/systems.php')) {
    require __DIR__.'/systems.php';
}

/*
|--------------------------------------------------------------------------
| Error pages
|--------------------------------------------------------------------------
|
| HTTP errors (403, 404, 500, 503, …) are not registered as routes. They are
| rendered by Inertia from AppServiceProvider via handleExceptionsUsing()
| and do not require authentication.
|
*/
